'use client'
import './globals.css'
import Header from '@/components/header/header'
import Footer from '@/components/footer'
import { ThemeProvider, createTheme } from '@mui/material/styles'
import { GlobalStyles } from '@mui/material'

const theme = createTheme({
  typography: {
    fontFamily: [
      'Nunito'
    ].join(',')
  },
  palette: {
    mode: 'light',
    primary: {
      main: '#59B376',
      contrastText: "#fff"
    },
    secondary: {
      main: '#EFDAA8',
    }
  },
  shape: {
    borderRadius: 10,
  },
  breakpoints: {
    values: {
      xs: 0,
      sm: 450,
      md: 700,
      lg: 1200,
      xl: 1536,
    }
  }
});

export const metadata = {
  title: 'Пластилин - десткий досуовый центр',
  description: 'Generated by create next app',

}

export default function RootLayout({ children }) {
  return (
    <html lang="ru">
      <body>
        <ThemeProvider theme={theme}>
          <Header />
          {children}
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  )
}
