import './globals.css'

export const metadata = {
  title: 'Пластилин - десткий досуговый центр',
  description: 'Generated by create next app',


}

export default function RootLayout({ children }) {
  return (
    <html lang="ru">
      <body>
        {children}
      </body>
    </html>
  )
}
